### ISSUE TITLE
Do not bind to any interface

### ISSUE THREAD

**Issue by scara** [dam2k/fanChat#1]
When running the fanChat daemon, it binds by default to TCP port 8888 on any local network interface, which should not be required since the daemon is local to the RPI.

PR is coming.

BTW, thanks a ton for this piece of software, actually valuable 👍!

HTH,
Matteo

**Comment by dam2k** [comment]
I don't see any socket binding on my RPI from fanChat, but it seams reasonable to accept your PR.
Thank you very much.

**Comment by scara** [comment]
TNX Dino!

Found while I tried to publish a port of a container by means of `-p "8888:9000"`.
Brand new _Buster Lite_, just installed your cool SW and then docker engine.

HTH,
Matteo
